#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ContosoInsurance.Droid.Resource", IsApplication=true)]

namespace ContosoInsurance.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::ContosoInsurance.Droid.Resource.String.library_name;
			global::Microsoft.WindowsAzure.Mobile.Files.Resource.String.ApplicationName = global::ContosoInsurance.Droid.Resource.String.ApplicationName;
			global::Microsoft.WindowsAzure.Mobile.Files.Resource.String.Hello = global::ContosoInsurance.Droid.Resource.String.Hello;
			global::PCLCrypto.Resource.String.ApplicationName = global::ContosoInsurance.Droid.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::ContosoInsurance.Droid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::ContosoInsurance.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::ContosoInsurance.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::ContosoInsurance.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AddNewImg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int CameraBk = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CameraBt = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int FocusAddNewImg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int forward = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int loginbackground = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int loginLogo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int navmenu = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int segement1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int segement2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int segement3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Settings = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030003
			public const int app_name = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int facebook_app_id = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fb_login_protocol_scheme = 2130903045;
			
			// aapt resource value: 0x7f030002
			public const int library_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
